# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Alex Chau
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/bay" # the subpath of the site
url: "https://eliottvincent.github.io" # the base hostname & protocol for the site
og_image: https://raw.githubusercontent.com/alexvchau/alexvchau.github.io/master/assets/img/0.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: alexchau21@gmail.com
      link: mailto:alexchau21@gmail.com
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/alexvchau
    - name: GitHub
      link: http://github.com/alexvchau


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
